version: 2.1

references:
  build_and_deliver_predev_filter: &build_and_deliver_predev_filter
    branches:
      only: /.*/

parameters:
  not_cleared_for_takeoff:
    type: boolean
    default: true
  run_build_tasks:
    type: boolean
    default: false
  run_release_tasks:
    type: boolean
    default: false

workflows:
  version: 2.1
  mission_control:
    when: << pipeline.parameters.not_cleared_for_takeoff >>
    jobs:
      - checkpoint
  
  build_and_deliver_predev-is_release_commit:
    when: << pipeline.parameters.run_release_tasks >>
    jobs:
      - check_pr_jira_ticket:
          filters:
            <<: *build_and_deliver_predev_filter
      - test_terraform:
          filters:
            <<: *build_and_deliver_predev_filter
      - test_azure_functions:
          filters:
            <<: *build_and_deliver_predev_filter
      - validate_circleci_config:
          filters:
            tags:
              only:
                - /predev-.*/
      - test_preflight:
          filters:
            <<: *build_and_deliver_predev_filter
  
  build_and_deliver_predev-not_release_commit:
    when: << pipeline.parameters.run_build_tasks >>
    jobs:
      - go_check:
          filters:
            <<: *build_and_deliver_predev_filter
      - go_sec:
          filters:
            <<: *build_and_deliver_predev_filter
      - bazel_integration:
          filters:
            <<: *build_and_deliver_predev_filter
      - go_coverage:
          filters:
            <<: *build_and_deliver_predev_filter
          requires:
            - bazel_integration
      - test_go_e2e:
          filters:
            <<: *build_and_deliver_predev_filter
      - test_cmd_cp-ui:
          filters:
            <<: *build_and_deliver_predev_filter
      # - test_go_integration_cp-ns TODO: uncomment when fixed.
      - mock_cypress_orb:
          name: "cp-ui functional test setup"
          filters:
            <<: *build_and_deliver_predev_filter
      # Use matrix jobs to create cp_ui_functional_tests
      - cp_ui_functional_test:
          matrix:
            parameters:
              testToRun: ["analytics", "app", "auth", "backups", "billing", "buckets", "clouds", "clusters", "confirmEmail", "dashboard", "documents", "flyouts","indexes", "invitations", "mainNavigation", "projects", "queryWorkbench", "session", "support", "tenants", "users", "services", "clusterWizard"]
          requires:
            - "cp-ui functional test setup"
          filters:
            <<: *build_and_deliver_predev_filter

jobs:
  checkpoint:
    machine: true
    steps:
      - run:
          name: Release Check
          command: |
            if git log -1 --pretty=%B | grep ".*\#release_commit.*";
            then
              echo "I'm a release commit - Run release tasks"
              curl -u ${CIRCLE_API_TOKEN}: -X POST --header "Content-Type: application/json" -d '{
                "parameters": {
                  "run_release_tasks": true,
                  "not_cleared_for_takeoff": false
                }
              }' https://circleci.com/api/v2/project/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline
            else
              echo "I'm not a release commit - Run build tasks"
              curl -u ${CIRCLE_API_TOKEN}: -X POST --header "Content-Type: application/json" -d '{
                "parameters": {
                  "run_build_tasks": true,
                  "not_cleared_for_takeoff": false
                }
              }' https://circleci.com/api/v2/project/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline
            fi

  check_pr_jira_ticket:
    machine: true
    steps:
      - run: echo gecko
  test_terraform:
    machine: true
    steps:
      - run: echo gecko
  test_azure_functions:
    machine: true
    steps:
      - run: echo gecko
  validate_circleci_config:
    machine: true
    steps:
      - run: echo gecko
  test_preflight:
    machine: true
    steps:
      - run: echo gecko
  go_check:
    machine: true
    steps:
      - run: echo gecko
  go_sec:
    machine: true
    steps:
      - run: echo gecko
  bazel_integration:
    machine: true
    steps:
      - run: echo gecko
  go_coverage:
    machine: true
    steps:
      - run: echo gecko
  test_go_e2e:
    machine: true
    steps:
      - run: echo gecko
  test_cmd_cp-ui:
    machine: true
    steps:
      - run: echo gecko
  cp_ui_functional_test:
    machine: true
    parameters:
      testToRun:
        type: string
        default: "*"
    steps:
      - run: echo << parameters.testToRun >>
  mock_cypress_orb:
    machine: true
    steps:
      - run: echo gecko
