# For transaction-grpc
# Recommendations:
#  - split build job into smaller jobs
#  - add workflows
#  - add test splitting based on timing 

version: 2
commands:
  stub:
    steps:
      - run: echo gecko
      
jobs:
  start_infra:
    docker:
      - image: circleci/node:10.15
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Start Support Infrastructure
          command: echo gecko
      - run:
          name: Dump SSH key
          command: echo gecko

  build_migrator:
    steps:
      - run:
          name: Build Migrator
          command: echo gecko

  build_image:
    steps:
      - setup_remote_docker
      - run:
          name: Build Image
          command: echo gecko

  build_test_image:
    steps:
      - setup_remote_docker
      - run:
          name: Build Test Image
          command: echo gecko
  
  test:
    steps:
      - run:
          name: Test
          command: echo gecko
      - store_test_results:
          path: /tmp/test_reports
      - store_artifacts:
          path: /tmp/test_reports
          destination: test_reports
  
  stop_infra:
    steps:
      - run:
          name: Stop Support Infrastructure
          when: always
          command: echo gecko

  tag_&_push:
    steps:
      - run:
          name: Tag & Push Image
          command: echo gecko

  dump_info:
    steps:
      - run:
          name: Dump deployment info
          command: echo gecko

  deploy:
    steps:
      - run:
          name: Deploy
          command: echo gecko

# workflows:
#   version: 2
#   build_test_and_deploy:
#     jobs: