# Recommendations for transaction-grpc:
#  - split build job into smaller jobs
#  - use workflow to orchestrate jobs
#  - explore test-splitting for long-running tests

version: 2
jobs:
  start_infra:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Start Support Infrastructure
          command: echo gecko
      - run:
          name: Dump SSH key
          command: echo gecko

  build_migrator:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Migrator
          command: echo gecko

  build_image:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Image
          command: echo gecko

  build_test_image:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Test Image
          command: echo gecko
  
  test_&_stop_infra:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Test
          command: echo gecko
      - store_test_results:
          path: /tmp/test_reports
      - store_artifacts:
          path: /tmp/test_reports
          destination: test_reports
      # - run:
      #     name: Force a failure
      #     command: exit 1
      - run:
          name: Stop Support Infrastructure
          when: always
          command: echo gecko

  tag_&_push:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Tag & Push Image
          command: echo gecko

  dump_deploy_info:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Dump deployment info
          command: echo gecko

  deploy:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo gecko

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - start_infra
      - build_migrator:
          requires:
            - start_infra
      - build_image:
          requires:
            - start_infra
      - build_test_image:
          requires:
            - start_infra
      - test_&_stop_infra:
          requires:
            - build_migrator
            - build_test_image
      - tag_&_push:
          requires:
            - test_&_push
      - dump_deploy_info:
          requires:
            - test_&_push
      - deploy:
          requires:
            - dump_deploy_info
            - tag_&_push